### ISSUE TITLE
ClientConnectorCertificateError

### ISSUE THREAD

**Issue by kirilkindan** [linkfy/threadspy#1]
Except: 
http.client_exceptions.ClientConnectorCertificateError: Cannot connect to host i.instagram.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')]

Process finished with exit code 1

**Comment by linkfy** [comment]
Updated, try the new commit.
